spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@example.com
      text: no-reply
  application:
    name: practice15
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: pass
    url: jdbc:postgresql://localhost:6666/postgres
  jpa:
    show-sql: true
server:
  port: 5556